pipeline {
  agent {
    kubernetes {
      label 'sampleapp'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  containers:
  - name: maven
    image: maven:latest
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: "/root/.m2"
        name: m2
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      persistentVolumeClaim:
        claimName: agent-custom-scratch-pvc
"""
}
   }
  stages {
    stage('Maven Build') {
      steps {
        container('maven') {
          sh """
                        ls
                        // mvn package -DskipTests
                                                """
        }
      }
    }
    stage('Test') {
      steps {
        container('maven') {
          sh """
            //  mvn test
            echo test
          """
        }
      }
    }
    stage('Docker Build') {
        container('docker') {
          sh """
             docker build -t sampleapp:$BUILD_NUMBER .
          """
        }
    }
  }
}