podTemplate {
    node(POD_LABEL) {
        stage('Checkout Source') {
            // Git fetch from main branch
            git(
                url: 'git@github.com:cronjevh/java-jenkins-techdemo.git',
                credentialsId: 'github-ssh',
                branch: 'extra-time'
              )
        }

        stage('Build') {
            // Docker Build - to local image only
            // sh 'docker build -f ./src/Dockerfile -t sampleapp:latest .'
            sh 'kubectl get pods'
        }
    }
}
