pipeline {
  agent {
    kubernetes {
      label 'maven'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  containers:
  - name: agent-custom
    image: cronjevh/agent-custom:latest
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: "/root/.m2"
        name: m2
      - mountPath: /var/run/docker.sock
        name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      persistentVolumeClaim:
        claimName: agent-custom-scratch-pvc
"""
}
   }
  stages {
    stage('Build') {
      steps {
        container('agent-custom') {
          sh """
                cd ./src/mavenitis && mvn exec:exec -q -Dexec.executable=docker-build.sh
                                                """
        }
      }
    }
    stage('Test') {
      steps {
        container('agent-custom') {
          sh """
            echo run tests
          """
        }
      }
    }
    stage('agent-custom') {
    steps {
        container('docker') {
          sh """
             kubectl scale deployment sampleapp-deploy --replicas=0 && kubectl scale deployment sampleapp-deploy --replicas=1
          """
        }
      }
    }
  }
}