apiVersion: v1
kind: Service
metadata:
  name: sampleapp-svc
spec:
  selector:
    app: sampleapp-deploy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30809
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 30810
  type: NodePort