apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sampleapp-pvc
  namespace: sampleapp
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
